insert into HUYỆT values(0, 1, 'tứ thần thông', 'đỉnh đầu, bách hội xiii 20 ra phải, trái, trước, sau 1 t. (hình n1)', '', 'châm nghiêng 0,5-1 t.');
insert into HUYỆT_CHỦ_TRỊ values(0, 1, 'đỉnh đầu đau');
insert into HUYỆT_CHỦ_TRỊ values(0, 1, 'điên');
insert into HUYỆT_CHỦ_TRỊ values(0, 1, 'động kinh');
insert into HUYỆT values(0, 2, 'ngư vĩ', 'vùng mặt, đuôi mắt, mép xương ngoài mi mắt ra 0,1t (hình n2)', '', 'châm 0,1-0,3t. không cứu');
insert into HUYỆT_CHỦ_TRỊ values(0, 2, 'xuất huyết võng mạc');
insert into HUYỆT_CHỦ_TRỊ values(0, 2, 'teo gai thị thần kinh giai đoạn đầu');
insert into HUYỆT values(0, 3, 'ngư yêu', 'vùng mặt, lông mày, đồng tử thẳng lên, chính giữa bờ lông mày (hình n2)', '', 'châm luồn dưới dac0,2-0,3t. không cứu');
insert into HUYỆT_CHỦ_TRỊ values(0, 3, 'sụp mi mắt');
insert into HUYỆT_CHỦ_TRỊ values(0, 3, 'mi mắt máy động');
insert into HUYỆT values(0, 4, 'ấn đường', 'vùng mặt, giữa 2 mắt, giữa đường nối hai đầu lông mày', '', 'châm chếch  0,1 t. cứu 5 - 10 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 4, 'đau đầu');
insert into HUYỆT_CHỦ_TRỊ values(0, 4, 'trẻ em kinh phong (?)');
insert into HUYỆT values(0, 5, 'thái dương', 'vùng mặt, chỗ lõm phía dưới ngoài đuôi long mày 1 t. đồng tử liêu xi 1(kinh đởm) ngang ra 0,5 t (hình n3)', '', 'châm 0,3-0,5 t hoặc chích huyết. cứu 5 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 5, 'glo côm');
insert into HUYỆT_CHỦ_TRỊ values(0, 5, 'đau đầu');
insert into HUYỆT values(0, 6, 'hiệp thừa tương', 'vùng mặt, hàm dưới, thữa tương xiv 24 ngang ra 1 t, địa thương iii 4  thẳng xuống (hình n3)', '', 'châm ngang về phía miệng  0,3-0,5 t.');
insert into HUYỆT_CHỦ_TRỊ values(0, 6, 'viêm lợi do vị nhiệt');
insert into HUYỆT_CHỦ_TRỊ values(0, 6, 'đau thần kinh tam thoa (?)');
insert into HUYỆT values(0, 7, 'tỵ thông', 'vùng mặt, cạnh sống mũi, chỗ lõm dưới xương mũi (hình n3)', '', 'châm men theo gốc mũi 0,5 t.');
insert into HUYỆT_CHỦ_TRỊ values(0, 7, 'viêm mũi dị ứng');
insert into HUYỆT values(0, 8, 'định suyễn', 'suyễn tức, xiii 14 đại chùy ngang ra hai bên 1 t', '', 'châm thẳng 0,3-0,5t. cứu 5 – 15 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 8, 'hen suyễn');
insert into HUYỆT_CHỦ_TRỊ values(0, 8, 'khó thở');
insert into HUYỆT values(0, 9, 'di tinh', 'bụng dưới rốn, xiv 4 quan nguyên ngang ra hai bên 1 t', '', 'châm thẳng 0,3-0,5 t.');
insert into HUYỆT_CHỦ_TRỊ values(0, 9, 'di tinh');
insert into HUYỆT_CHỦ_TRỊ values(0, 9, 'liệt dương');
insert into HUYỆT_CHỦ_TRỊ values(0, 9, 'xuất tinh nhanh');
insert into HUYỆT values(0, 10, 'hoa đà giáp tích', 'từ ngang mỏm vai đốt sống lưng 1 (d1) đến đốt sống thắt lưng 5 (l5) đều ngang ra 0,5 t. mỗi bên 17 huyệt, hai bên 34 huyệt.', '', 'châm, cứu hoặc dùng kim hoa mai gõ thường quy(?)');
insert into HUYỆT_CHỦ_TRỊ values(0, 10, 'tác dụng gần như du huyệt kinh bang quang');
insert into HUYỆT values(0, 11, 'khí suyễn', 'vùng lưng vai, dưới gai đốt sống lưng thứ 7 (d7) ngang ra 2 t (hình n4)', '', 'châm nghiêng 0,5-1 t. cứu 5 – 15 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 11, 'hen suyễn nặng');
insert into HUYỆT values(0, 12, 'tứ hoa', 'vùng lưng, gồm vii 17 cách du và vii 19 đởm du (kinh bàng quang)', '', 'cứu 15 – 20 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 12, 'viêm phế quản');
insert into HUYỆT_CHỦ_TRỊ values(0, 12, 'cơ thể suy nhược');
insert into HUYỆT values(0, 13, 'kị trúc mã', 'vùng lưng, dưới mỏm gai đốt sống lưng thứ 10 (d10) ngang ra 0,5 t. hình n4', '', 'châm  0,5-1 t. cứu 15 -20 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 13, 'ung nhọt');
insert into HUYỆT_CHỦ_TRỊ values(0, 13, 'tràng nhạc (?)');
insert into HUYỆT values(0, 14, 'bĩ căn', 'vùng thắt lưng, dưới mỏm gai đốt sống thắt lưng thứ 1 (l1) ngang ra hai bên 0,5 t.', '', 'châm thẳng 1-1,5 t.');
insert into HUYỆT_CHỦ_TRỊ values(0, 14, 'gan');
insert into HUYỆT_CHỦ_TRỊ values(0, 14, 'tỳ chướng');
insert into HUYỆT_CHỦ_TRỊ values(0, 14, 'viêm đường ruột');
insert into HUYỆT values(0, 15, 'yêu nhãn', 'vùng thắt lưng, mỏm gai đốt sống thắt lưng thứ 4 (l4) ngang ra 3,8 t', '', 'châm  0,5-1 t. cứu 15 -20 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 15, 'đau thắt lưng');
insert into HUYỆT_CHỦ_TRỊ values(0, 15, 'sưng tinh hoàn');
insert into HUYỆT values(0, 16, 'tinh cung', 'vùng thắt lưng, vii 52 chí thất ngang ra 0,5 t', '', 'châm 1-1,5 t. cứu 5 -10 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 16, 'di tinh');
insert into HUYỆT_CHỦ_TRỊ values(0, 16, 'hoạt tinh');
insert into HUYỆT_CHỦ_TRỊ values(0, 16, 'liệt dương');
insert into HUYỆT values(0, 17, 'hoàn trung', 'vùng hông, giữa đường nối xi 30 hoàn khiêu và xiii 2 yêu du', '', 'châm thẳng 2-3 t.');
insert into HUYỆT_CHỦ_TRỊ values(0, 17, 'thần kinh tọa');
insert into HUYỆT_CHỦ_TRỊ values(0, 17, 'đau lưng');
insert into HUYỆT values(0, 18, 'thập nhị tinh', 'gồm i 11 thiếu thương, ii 1 thương dương, ix 9 trung xung, x 1 quan xung, v 9 thiếu xung, vi 1 thiếu trạch, cộng 2 bên lại 12 huyệt', '', 'chích huyết');
insert into HUYỆT_CHỦ_TRỊ values(0, 18, 'các chứng hôn mê');
insert into HUYỆT_CHỦ_TRỊ values(0, 18, 'kinh phong');
insert into HUYỆT_CHỦ_TRỊ values(0, 18, 'sốt cao');
insert into HUYỆT values(0, 19, 'lạc chẩm', 'trên mu bàn tay, giữa khe ngón trỏ và ngón giữa ngang với trung chữ', '', 'châm thẳng 0,4-0,5 t. cứu 5- 10 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 19, 'đau vùng gáy');
insert into HUYỆT values(0, 20, 'tứ phùng', 'bàn tay, trên ngón tay, giữa lằn chỉ mặt trước khớp đốt 1 và 2 các ngón 2, 3, 4, 5 (hình n5)', '', 'chích huyết. không cứu');
insert into HUYỆT_CHỦ_TRỊ values(0, 20, 'cam tích trẻ em(?)');
insert into HUYỆT values(0, 21, 'thập tuyên', 'mười đầu ngón tay, đỉnh cao nhất giữa 10 đầu ngón tay', '', 'dung kim chích huyết');
insert into HUYỆT_CHỦ_TRỊ values(0, 21, 'sốt cao');
insert into HUYỆT_CHỦ_TRỊ values(0, 21, 'hôn mê');
insert into HUYỆT_CHỦ_TRỊ values(0, 21, 'viêm amidan');
insert into HUYỆT values(0, 22, 'bát tà', 'trên mu bàn tay  kẽ ngón tay, kẽ 5 ngón tay mối bên có 4 huyệt. đại đô ở hổ khẩu, giữa ngón trỏ và ngón cái. thượng đô ở kẽ ngón trỏ và ngón giữa, trung đô ở kẽ ngón giữa và ngón đeo nhẫn, hạ đô ở kẽ ngón nhẫn và ngón út. (hình n5)', '', 'châm 0,1-0,5 t. cứu 5 -15 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 22, 'tê sưng ngón tay');
insert into HUYỆT_CHỦ_TRỊ values(0, 22, 'liệt do trúng phong. ngoài ra đại đo chữa đau đầu và đau răng. thượng đô');
insert into HUYỆT_CHỦ_TRỊ values(0, 22, 'trung đô');
insert into HUYỆT_CHỦ_TRỊ values(0, 22, 'hạ đô chữa đau sưng cánh tay');
insert into HUYỆT values(0, 23, 'nhị bạch', 'vùng cổ tay, mặt trong, nếp gấp cổ tay lên 4 t, một huyệt lấy ở bờ ngoài cơ gan tay bé, và một huyệt lấy ở bờ trong. (hình n5)', '', 'châm 0,5-1 t. cứu 10- 15 phút, không kích thích quá mạnh');
insert into HUYỆT_CHỦ_TRỊ values(0, 23, 'trĩ hạ (?)');
insert into HUYỆT_CHỦ_TRỊ values(0, 23, 'lòi dom');
insert into HUYỆT values(0, 24, 'lan vĩ', 'vùng đầu gối cẳng chân, iii 36 túc tam lý (kinh vị) xuống 2 t', '', 'châm thẳng 1-1,5 t.');
insert into HUYỆT_CHỦ_TRỊ values(0, 24, 'viêm ruột thừa cấp');
insert into HUYỆT values(0, 25, 'đởm nang', 'túi mật, mặt ngoài cẳng chân, chỗ lõm bờ trước đầu xương mác xuống 2 t', '', 'châm 0,5-1,5 t');
insert into HUYỆT_CHỦ_TRỊ values(0, 25, 'viêm túi mật');
insert into HUYỆT_CHỦ_TRỊ values(0, 25, 'giun chui ống mật');
insert into HUYỆT values(0, 26, 'túc trung bình', 'vùng đầu gối, iii 36 túc tam lý (kinh vị) xuống  1 t', '', 'châm thẳng 2-3 t.');
insert into HUYỆT_CHỦ_TRỊ values(0, 26, 'bệnh tâm thần');
insert into HUYỆT_CHỦ_TRỊ values(0, 26, 'chi dưới tê bại');
insert into HUYỆT values(0, 27, 'bát phong', 'kẽ ngón chân, kẽ 5 đầu ngón chân, chỗ tiếp giáp của da mu bàn chân và da gan bàn chân', '', 'châm thẳng 0,1-0,3 t hoặc chích huyết');
insert into HUYỆT_CHỦ_TRỊ values(0, 27, 'bàn chân sưng đỏ');
insert into HUYỆT values(0, 28, 'bách trùng oa', 'vùng đùi trên đầu gối bên trong, huyết hải iv 10 lên 1 t', '', 'châm 0,5-1,5 t. cứu 5 -10 phút');
insert into HUYỆT_CHỦ_TRỊ values(0, 28, 'mụn nhọt ở hạ bộ');
insert into HUYỆT_CHỦ_TRỊ values(0, 28, 'một số bệnh viêm nhiễm');
insert into HUYỆT values(0, 29, 'tứ quan', 'mu bàn tay, hai huyệt ii 4 hợp cốc (mu bàn tay) và xii 3 thái xung (mu bàn chân)', '', 'như hợp cốc ii 4, thái xung xii 3');
insert into HUYỆT_CHỦ_TRỊ values(0, 29, 'phong');
insert into HUYỆT_CHỦ_TRỊ values(0, 29, 'hàn');
insert into HUYỆT_CHỦ_TRỊ values(0, 29, 'thấp');
insert into HUYỆT_CHỦ_TRỊ values(0, 29, 'tý (?). có giá trị như huyệt mở (?)');
