insert into NHOM_BENH values('cảm cúm', 'cảm mạo (phong hàn thấp)','');
insert into NHOM_BENH values('cảm cúm', 'cúm (phong nhiệt)','');
insert into NHOM_BENH values('viêm phế quản', 'viêm phế quản cấp tính viêm phế quản do phong hàn','');
insert into NHOM_BENH values('viêm phế quản', 'viêm phế quản cấp tính viêm phế quản do phong nhiệt','');
insert into NHOM_BENH values('viêm phế quản', 'viêm phế quản cấp tính viêm phế quản do thủy ẩm (hàn ẩm)','');
insert into NHOM_BENH values('viêm phế quản', 'viêm phế quản cấp tính viêm phế quản do khí táo (?)','');
insert into NHOM_BENH values('viêm phế quản', 'viêm phế quản mãn viêm phế quản do tyd dương hư, đờm thấp','');
insert into NHOM_BENH values('hen phế quản', 'hen phế quản khi đang lên cơn (thực chứng) hen hàn (lãnh háo)','');
insert into NHOM_BENH values('hen phế quản', 'hen phế quản khi đang lên cơn (thực chứng) hen nhiệt (nhiệt háo)','');
insert into NHOM_BENH values('hen phế quản', 'hen phế quản khi đã đỡ cơn hen (hư chứng) phế khí hư','');
insert into NHOM_BENH values('hen phế quản', 'hen phế quản khi đã đỡ cơn hen (hư chứng) phế âm hư','');
insert into NHOM_BENH values('hen phế quản', 'hen phế quản khi đã đỡ cơn hen (hư chứng) tỳ dương hư','');
insert into NHOM_BENH values('hen phế quản', 'hen phế quản khi đã đỡ cơn hen (hư chứng) thận dương hư','');
insert into NHOM_BENH values('hen phế quản', 'hen phế quản khi đã đỡ cơn hen (hư chứng) thận âm hư','');
insert into NHOM_BENH values('hen phế quản', 'hen phế quản (asthma)','mục 4 – 1');
insert into NHOM_BENH values('nấc', 'nấc','');
insert into NHOM_BENH values('hội chứng dạ dày (vị quản thống – vị thống)', 'can khí phạm vị khí trệ','');
insert into NHOM_BENH values('hội chứng dạ dày (vị quản thống – vị thống)', 'can khí phạm vị hỏa uất','');
insert into NHOM_BENH values('hội chứng dạ dày (vị quản thống – vị thống)', 'can khí phạm vị huyết ứ','');
insert into NHOM_BENH values('hội chứng dạ dày (vị quản thống – vị thống)', 'can khí phạm vị hư chứng (thể hoãn)','');
insert into NHOM_BENH values('hội chứng dạ dày (vị quản thống – vị thống)', 'can khí phạm vị tỳ vị hư hàn','');
insert into NHOM_BENH values('hội chứng dạ dày (vị quản thống – vị thống)', 'đau dạ dày mãn tính (chronic gastritis)','mục 3 – 19');
insert into NHOM_BENH values('hội chứng dạ dày (vị quản thống – vị thống)', 'đau dạ dày co thắt (stomach cramps)','mục 3 – 20');
insert into NHOM_BENH values('hội chứng dạ dày (vị quản thống – vị thống)', 'đau dạ dày – hành tá tràng  (stomach cramps)','mục 4 – 2');
insert into NHOM_BENH values('đau bụng cấp (phúc thống)', 'đau bụng cảm hàn','');
insert into NHOM_BENH values('đau bụng cấp (phúc thống)', 'đau bụng do tỳ vị hư hàn','');
insert into NHOM_BENH values('đau bụng cấp (phúc thống)', 'đau bụng do thực tích','');
insert into NHOM_BENH values('đau bụng cấp (phúc thống)', 'đau bụng do trùng tích (giun)','');
insert into NHOM_BENH values('đau bụng cấp (phúc thống)', 'đau bụng do khí trệ','');
insert into NHOM_BENH values('đau bụng cấp (phúc thống)', 'đau bụng do huyết ứ','');
insert into NHOM_BENH values('ỉa chảy', 'ỉa chảy cấp ỉa chảy do hàn','');
insert into NHOM_BENH values('ỉa chảy', 'ỉa chảy cấp ỉa chảy do nhiệt thử','');
insert into NHOM_BENH values('ỉa chảy', 'ỉa chảy cấp ỉa chảy do thấp trệ (?)','');
insert into NHOM_BENH values('ỉa chảy', 'ỉa chảy mãn tính tỳ hư','');
insert into NHOM_BENH values('ỉa chảy', 'ỉa chảy mãn tính thận dương hư (mệnh môn hỏa suy)','');
insert into NHOM_BENH values('ỉa chảy', 'ỉa chảy mãn tính ỉa chảy mãn do can tỳ bất hỏa','');
insert into NHOM_BENH values('ỉa chảy', 'ỉa chảy mãn tính (chronic diarrhea)','mục 3 – 21');
insert into NHOM_BENH values('hội chứng lị (a míp, trực khuẩn)', 'lị cấp tính lị do hàn thấp (bạch lị)','');
insert into NHOM_BENH values('hội chứng lị (a míp, trực khuẩn)', 'lị cấp tính lị do thấp  nhiệt (xích bạch lị)','');
insert into NHOM_BENH values('hội chứng lị (a míp, trực khuẩn)', 'lị cấp tính lị do dịch độc (xích lị)','');
insert into NHOM_BENH values('hội chứng lị (a míp, trực khuẩn)', 'lị cấp tính lị cấm khẩu','');
insert into NHOM_BENH values('hội chứng lị (a míp, trực khuẩn)', 'lị mãn tính (hưu tức lị)','');
insert into NHOM_BENH values('táo bón', 'thực chứng','');
insert into NHOM_BENH values('táo bón', 'hư chứng táo bón do âm hư huyết nhiệt (?)','');
insert into NHOM_BENH values('táo bón', 'hư chứng táo bón do dương khí hư (ở người già, suy nhược, phụ nữ đẻ nhiều lần)','');
insert into NHOM_BENH values('táo bón', 'táo bón (cosntipation)','mục 3 – 22');
insert into NHOM_BENH values('táo bón', 'táo bón (cosntipation)','mục 4 – 18');
insert into NHOM_BENH values('lòi dom', 'thực chứng (thường gặp ở những người trẻ tuổi)','');
insert into NHOM_BENH values('lòi dom', 'hư chứng (ngươig già yếu, trẻ em khí hư)','');
insert into NHOM_BENH values('lòi dom', 'trĩ (hemerrhoid)','mục 3 – 23');
insert into NHOM_BENH values('bí tiểu tiện', 'nhiêm khuẩn đường tiết niệu','');
insert into NHOM_BENH values('bí tiểu tiện', 'sỏi đường tiết niệu, sang chấn (có thể dung cho hậu phẫu)','');
insert into NHOM_BENH values('bí tiểu tiện', 'phế khí không giáng (?)','');
insert into NHOM_BENH values('bí tiểu tiện', 'do thận hư (hay gặp ở người già)','');
insert into NHOM_BENH values('bí tiểu tiện', 'phụ nữ có mang bí tiểu','');
insert into NHOM_BENH values('bí tiểu tiện', 'bí tiểu tiện (retention of urine)','mục 4 – 19');
insert into NHOM_BENH values('đau lưng', 'đau lưng (lumbago)','mục 3 – 11');
insert into NHOM_BENH values('đau lưng', 'đau vai lưng (aching back and shoulder)','mục 3 – 12');
insert into NHOM_BENH values('đau lưng', 'đau lưng cấp (acute pain in the back)','mục 3 – 13');
insert into NHOM_BENH values('đau lưng', 'đau vùng lưng dưới (mild pain in the lower back)','mục 3 – 14');
insert into NHOM_BENH values('đau lưng', 'đau lưng do hàn thấp','');
insert into NHOM_BENH values('đau lưng', 'đau lưng cấp do chấn thương, huyết ứ','');
insert into NHOM_BENH values('đau lưng', 'đau lưng do thận hư','');
insert into NHOM_BENH values('đau lưng', 'đau lưng dưới (lumbago)','mục 4 – 3');
insert into NHOM_BENH values('đau dây thần kinh hông', 'do phong hàn','');
insert into NHOM_BENH values('đau dây thần kinh hông', 'thoái hóa cột sống gây chèn ép','');
insert into NHOM_BENH values('đau dây thần kinh hông', 'đau dây thần kinh hông (sciatica)','mục 3 – 16');
insert into NHOM_BENH values('đau dây thần kinh hông', 'đau dây thần kinh hông (sciatica)','mục 4 – 4');
insert into NHOM_BENH values('đau dây thần kinh hông', 'chân và hông yếu mỏi (fatigue in legs and híp)','mục 3 – 17');
insert into NHOM_BENH values('đau dây thần kinh hông', 'đau gối (pains in the knee)','mục 3 – 18');
insert into NHOM_BENH values('đau dây thần kinh liên sườn (hiếp thống)', 'can khí uất nghịch','');
insert into NHOM_BENH values('đau dây thần kinh liên sườn (hiếp thống)', 'đờm ẩm','');
insert into NHOM_BENH values('đau dây thần kinh liên sườn (hiếp thống)', 'ứ huyết','');
insert into NHOM_BENH values('đau dây thần kinh liên sườn (hiếp thống)', 'đauthần kinh liên sườn (intercostal neuralgia)','mục 3 – 15');
insert into NHOM_BENH values('đau dây thần kinh liên sườn (hiếp thống)', 'đauthần kinh liên sườn (interseatical neuralgia)','mục 4 – 5');
insert into NHOM_BENH values('vẹo cổ cấp', 'vẹo cổ cấp (whiplash sundrome)','mục 3 – 6');
insert into NHOM_BENH values('hội chứng cổ tay, vai vận động hạn chế', 'đau cứng cổ, vai và cánh tay (pains and stiffness in the neck, shoulders and arms)','mục 3 – 7');
insert into NHOM_BENH values('hội chứng cổ tay, vai vận động hạn chế', 'đau gáy, cổ, vai (stiff shoulders)','mục 3 – 8');
insert into NHOM_BENH values('hội chứng cổ tay, vai vận động hạn chế', 'tê cánh tay (numbness in the arms)','mục 3 – 9');
insert into NHOM_BENH values('hội chứng cổ tay, vai vận động hạn chế', 'viêm thần kinh cánh tay (neuralgia in the arms)','mục 3 – 10');
insert into NHOM_BENH values('hội chứng cổ tay, vai vận động hạn chế', 'chứng hư ( hàn)','');
insert into NHOM_BENH values('hội chứng cổ tay, vai vận động hạn chế', 'chứng thực (nhiệt)','');
insert into NHOM_BENH values('hội chứng cổ tay, vai vận động hạn chế', 'hội chứng đau và hạn chế vận động cổ, vai, cánh tay','mục 4 – 6');
insert into NHOM_BENH values('đau nhức xương cơ khớp (chứng tý)', 'phong tý (hành tý)','');
insert into NHOM_BENH values('đau nhức xương cơ khớp (chứng tý)', 'hàn tý (thống tý)','');
insert into NHOM_BENH values('đau nhức xương cơ khớp (chứng tý)', 'thấp tý (trước tý)','');
insert into NHOM_BENH values('đau nhức xương cơ khớp (chứng tý)', 'viêm khớp dạng thấp (phong thấp nhiệt tý )','');
insert into NHOM_BENH values('đau nhức xương cơ khớp (chứng tý)', 'đau nhức xương , khớp khớp vai (thêm các huyệt):','mục 4 – 7 a)');
insert into NHOM_BENH values('đau nhức xương cơ khớp (chứng tý)', 'đau nhức xương , khớp khớp gối (thêm các huyệt)','mục 4 – 7 b)');
insert into NHOM_BENH values('đau nhức xương cơ khớp (chứng tý)', 'đau nhức xương , khớp khớp háng (thêm các huyệt)','mục 4 – 7 c)');
insert into NHOM_BENH values('đau nhức xương cơ khớp (chứng tý)', 'đau nhức xương , khớp khớp cổ tay  (thêm các huyệt)','mục 4 – 7 d)');
insert into NHOM_BENH values('đau nhức xương cơ khớp (chứng tý)', 'đau nhức xương , khớp khớp cổ chân (thêm các huyệt)','mục 4 – 7 e)');
insert into NHOM_BENH values('suy nhược thần kinh', 'can tâm khí uất kết','');
insert into NHOM_BENH values('suy nhược thần kinh', 'tâm can thận âm hư thận âm hư, can dương vượng','');
insert into NHOM_BENH values('suy nhược thần kinh', 'tâm can thận âm hư tâm canthận âm hư','');
insert into NHOM_BENH values('suy nhược thần kinh', 'tâm can thận âm hư tâm tỳ hư','');
insert into NHOM_BENH values('suy nhược thần kinh', 'tâm can thận âm hư thận khí hư (âm dương lưỡng hư)','');
insert into NHOM_BENH values('suy nhược thần kinh', 'suy nhược thần kinh (neurasthenia)','mục 4 – 8');
insert into NHOM_BENH values('suy nhược thần kinh', 'nôn nao  (hangover)','mục 3 - 27');
insert into NHOM_BENH values('suy nhược thần kinh', 'loạn thần kinh chức năng  (neurosis )','mục 3 – 20');
insert into NHOM_BENH values('mất ngủ', 'mất ngủ do tâm huyết hư tổn','');
insert into NHOM_BENH values('mất ngủ', 'mất ngủ do tâm thận bất giao','');
insert into NHOM_BENH values('mất ngủ', 'mất ngủ do tỳ vị bất hòa','');
insert into NHOM_BENH values('mất ngủ', 'mất ngủ do can đởm hỏa vượng thực chứng','');
insert into NHOM_BENH values('mất ngủ', 'mất ngủ do can đởm hỏa vượng hư chứng','');
insert into NHOM_BENH values('mất ngủ', 'mất  ngủ  (insomnia)','mục 3 - 28');
insert into NHOM_BENH values('mất ngủ', 'mất  ngủ  (insomnia)','mục 4 – 21');
insert into NHOM_BENH values('mất ngủ', 'kém ăn  (loss of appetite)','mục 3 - 29');
insert into NHOM_BENH values('đau đầu', 'đau đầu','mục 3-1');
insert into NHOM_BENH values('đau đầu', 'thực chứng ngoại cảm phong tà','');
insert into NHOM_BENH values('đau đầu', 'thực chứng đờm trọc thực tích (?)','');
insert into NHOM_BENH values('đau đầu', 'thực chứng can khí thượng nghịch (?)','');
insert into NHOM_BENH values('đau đầu', 'hư chứng khí hư','');
insert into NHOM_BENH values('đau đầu', 'hư chứng huyết hư','');
insert into NHOM_BENH values('đau đầu', 'đau đầu  (headaches) đau đỉnh đầu (do can, thêm các huyệt)','mục 4 – 9 a)');
insert into NHOM_BENH values('đau đầu', 'đau đầu  (headaches) đau  đầu vùng gáy (thêm các huyệt)','mục 4 – 9 b)');
insert into NHOM_BENH values('đau đầu', 'đau đầu  (headaches) đau vùng trán, thái dương (thêm các huyệt)','mục 4 – 9 c)');
insert into NHOM_BENH values('đau đầu', 'đau đầu  (headaches) đau  đầu mignaire (thêm các huyệt)','mục 4 – 9 d)');
insert into NHOM_BENH values('đau đầu', 'đau đầu  (headaches) đau  đầu vùng gáy (?)  (thêm các huyệt)','mục 4 – 9 e)');
insert into NHOM_BENH values('đau dây thần kinh tam thoa', 'đau dây thần kinh tam thoa (trigeminal neuralgia)','mục 3 – 4');
insert into NHOM_BENH values('đau dây thần kinh tam thoa', 'đau dây thần kinh tam thoa nhánh dưới ( thêm các huyệt)','mục 4 – 10');
insert into NHOM_BENH values('đau dây thần kinh tam thoa', 'đau dây thần kinh tam thoa nhánh giữa( thêm các huyệt)','mục 4 – 10');
insert into NHOM_BENH values('hội chứng mê ni e (meniere) (huyễn vựng)', 'can phong:','');
insert into NHOM_BENH values('hội chứng mê ni e (meniere) (huyễn vựng)', 'đờm thấp (?)','');
insert into NHOM_BENH values('hội chứng mê ni e (meniere) (huyễn vựng)', 'huyết hư','');
insert into NHOM_BENH values('liệt dây vii ngoại biên (khẩu nhãn oa tà)', 'liệt dây vii ngoại biên (facial nerve paralysis)','mục 3 – 5');
insert into NHOM_BENH values('liệt dây vii ngoại biên (khẩu nhãn oa tà)', 'liệt dây vii do lạnh','');
insert into NHOM_BENH values('liệt dây vii ngoại biên (khẩu nhãn oa tà)', 'liệt dây vii do nhiễm trùng','');
insert into NHOM_BENH values('liệt dây vii ngoại biên (khẩu nhãn oa tà)', 'liệt dây vii do sang chấn (?)','');
insert into NHOM_BENH values('liệt dây vii ngoại biên (khẩu nhãn oa tà)', 'liệt dây vii ngoại biên (facial peripheral paralysis)','mục 4 – 12');
insert into NHOM_BENH values('huyết áp cao  (high blood pressure)', 'huyết áp cao  (high blood pressure)','mục 3 - 31');
insert into NHOM_BENH values('huyết áp thấp (low blood pressure)', 'huyết áp thấp (low blood pressure)','mục 3 - 32');
insert into NHOM_BENH values('tai biến mạch máu não (trúng phong)', 'trúng phong kinh lạc (?)','');
insert into NHOM_BENH values('tai biến mạch máu não (trúng phong)', 'trúng phong tạng phủ chứng bế (hôn mê nông)','');
insert into NHOM_BENH values('tai biến mạch máu não (trúng phong)', 'trúng phong tạng phủ chứng thoát (hôn mê sâu)','');
insert into NHOM_BENH values('tai biến mạch máu não (trúng phong)', 'trúng phong tạng phủ giai đoạn di chứng','');
insert into NHOM_BENH values('tai biến mạch máu não (trúng phong)', 'trúng phong tạng phủ phòng bệnh trúng phong','');
insert into NHOM_BENH values('tai biến mạch máu não (trúng phong)', 'tai biến mạch máu não (cerebral vascular accident) liệt nửa người','mục 4 – 13');
insert into NHOM_BENH values('tai biến mạch máu não (trúng phong)', 'tai biến mạch máu não (cerebral vascular accident) nếu có cấm khẩu khó nói (thêm các huyệt)','mục 4 – 13');
insert into NHOM_BENH values('tai biến mạch máu não (trúng phong)', 'tai biến mạch máu não (cerebral vascular accident) nếu có liệt mặt','mục 4 – 13');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt trước kỳ huyết nhiệt (thực nhiệt)','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt trước kỳ âm hư, huyết nhiệt (hư nhiệt)','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt trước kỳ do khí hư','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt sau kỳ (thường gặp thể hư hàn) do hàn hư hàn:','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt sau kỳ (thường gặp thể hư hàn) do hàn phong hàn (thưc)','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt sau kỳ (thường gặp thể hư hàn) do huyết huyết ứ (thực)','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt sau kỳ (thường gặp thể hư hàn) do huyết huyết hư','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt sau kỳ (thường gặp thể hư hàn) đàm thấp','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt sau kỳ (thường gặp thể hư hàn) khí uất','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'rối loạn kinh nguyệt can khí uất kết','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'rối loạn kinh nguyệt tỳ hư','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'rối loạn kinh nguyệt can thận hư','');
insert into NHOM_BENH values('kinh nguyệt không đều', 'kinh nguyệt không đều (irregular menstruation)','mục 4 – 14');
insert into NHOM_BENH values('khí hư', 'nhiễm khuẩn','');
insert into NHOM_BENH values('khí hư', 'can uất','');
insert into NHOM_BENH values('khí hư', 'đàm thấp (?)','');
insert into NHOM_BENH values('khí hư', 'tỳ hư','');
insert into NHOM_BENH values('khí hư', 'thận hư thận dương (?) hư','');
insert into NHOM_BENH values('khí hư', 'thận hư thận âm (?) hư','');
insert into NHOM_BENH values('tắc tia sữa', 'tắc tia sữa','');
insert into NHOM_BENH values('sốt cao co giật trẻ em (cấp kinh phong)', 'sốt cao co giật trẻ em (cấp kinh phong)','');
insert into NHOM_BENH values('ho gà (bách nhật khái)', 'giai đoạn sơ nhiễm','');
insert into NHOM_BENH values('ho gà (bách nhật khái)', 'giai đoạn ho cơn','');
insert into NHOM_BENH values('ho gà (bách nhật khái)', 'giai đoạn phục hồi','');
insert into NHOM_BENH values('đái dầm', 'thận khí hư hàn','');
insert into NHOM_BENH values('đái dầm', 'do phế tỳ khí hư','');
insert into NHOM_BENH values('đái dầm', 'do can khí uất nhiệt','');
insert into NHOM_BENH values('quai bị', 'quai bị','');
insert into NHOM_BENH values('viêm não nhật bản b', 'giai đoạn cấp tính thể vệ khí (khởi phát chưa có biến chứng)','');
insert into NHOM_BENH values('viêm não nhật bản b', 'giai đoạn cấp tính thể doanh huyết (toàn phát có biến chứng)','');
insert into NHOM_BENH values('viêm não nhật bản b', 'giai đoạn hồi phục và di chứng','');
insert into NHOM_BENH values('di chứng bại liệt trẻ em (giai đoạn đầu trong vòng 6 tháng)', 'di chứng bại liệt trẻ em (giai đoạn đầu trong vòng 6 tháng)','');
insert into NHOM_BENH values('cận thị trẻ em', 'cận thị trẻ em','');
insert into NHOM_BENH values('mỏi mắt', 'mỏi mắt','mục 3 -2');
insert into NHOM_BENH values('viêm kết mạc (thiên hành xích nhãn)', 'viêm kết mạc thể cấp','');
insert into NHOM_BENH values('viêm kết mạc (thiên hành xích nhãn)', 'viêm kết mạc thể bán cấp và mãn','');
insert into NHOM_BENH values('đục nhân mắt (không có biến chứng)', 'đục nhân mắt (không có biến chứng)','');
insert into NHOM_BENH values('viêm võng mạc trung tâm', 'viêm võng mạc trung tâm','');
insert into NHOM_BENH values('viêm mũi cấp (viêm mũi dị ứng)', 'viêm mũi dị ứng (allergie rhinitis)','mục 4 – 15');
insert into NHOM_BENH values('viêm xoang cấp', 'viêm xoang dị ứng','');
insert into NHOM_BENH values('viêm xoang cấp', 'viêm xoang nhiễm khuẩn','');
insert into NHOM_BENH values('viêm xoang cấp', 'viêm xoang dị ứng (allergie sinusitis)','mục 4 – 16');
insert into NHOM_BENH values('viêm họng', 'viêm họng cấp','');
insert into NHOM_BENH values('viêm họng', 'viêm họng mãn tính','');
insert into NHOM_BENH values('viêm thanh quản (thất âm)', 'loại cấp (thực chứng) phong hàn','');
insert into NHOM_BENH values('viêm thanh quản (thất âm)', 'loại cấp (thực chứng) đờm nhiệt','');
insert into NHOM_BENH values('viêm thanh quản (thất âm)', 'loại mãn (hư chứng) phế âm hư','');
insert into NHOM_BENH values('viêm thanh quản (thất âm)', 'loại mãn (hư chứng) thận âm hư','');
insert into NHOM_BENH values('viêm thanh quản (thất âm)', 'viêm thanh quản (laryngitis)','mục 4 – 17');
insert into NHOM_BENH values('viêm a mi đan cấp', 'thể nhẹ','');
insert into NHOM_BENH values('viêm a mi đan cấp', 'thể nặng','');
insert into NHOM_BENH values('đau răng -', 'đau răng –toothache','mục 3 -3');
insert into NHOM_BENH values('đau răng -', 'đau răng cấp tính (thực chứng)','');
insert into NHOM_BENH values('đau răng -', 'đau răng mãn (hư chứng) đau sau nhổ răng','');
insert into NHOM_BENH values('viêm lợi cấp (phong nhiệt nha cam)', 'viêm lợi cấp (phong nhiệt nha cam)','');
insert into NHOM_BENH values('mề đay (phong chẩn khối)', 'thể phong hàn','');
insert into NHOM_BENH values('mề đay (phong chẩn khối)', 'thể phong nhiệt','');
insert into NHOM_BENH values('mề đay (phong chẩn khối)', 'hội chứng mề đay dị ứng (allergy urticaria)','mục 4 – 11');
insert into NHOM_BENH values('trợ dương (increasing potency)', 'trợ dương (increasing potency)','mục 3 - 24');
insert into NHOM_BENH values('liêt dương (impotence)', 'liêt dương (impotence)','mục 3 - 25');
insert into NHOM_BENH values('lãnh dục nữ (frigidity)', 'lãnh dục nữ (frigidity)','mục 3 - 26');
insert into NHOM_BENH values('quá béo  (reducing weight)', 'quá béo  (reducing weight)','mục 3 - 33');
insert into NHOM_BENH values('giảm béo  (reducing weight)', 'giảm béo  (reducing weight)','mục 4 – 20');
insert into NHOM_BENH values('nâng cao chính khí (rétoring vitality)', 'nâng cao chính khí (rétoring vitality)','mục 3 - 34');
insert into NHOM_BENH values('bệnh trẻ em (disease of the children)', 'bại liệt (poliomyelitis) – chi dưới','mục 4 – 22 a)');
insert into NHOM_BENH values('bệnh trẻ em (disease of the children)', 'bại liệt (poliomyelitis) – chi trên (arms)','mục 4 – 22 b)');
insert into NHOM_BENH values('bệnh trẻ em (disease of the children)', 'điếc (deafness)','mục 4 – 22 c)');
insert into NHOM_BENH values('bệnh trẻ em (disease of the children)', 'lác (strabismus)','mục 4 – 22 d)');
insert into NHOM_BENH values('bệnh trẻ em (disease of the children)', 'sụp mi mắt (sptosis)','mục 4 – 22 e)');
insert into NHOM_BENH values('bệnh trẻ em (disease of the children)', 'câm, chậm nói (psychomotor retardation language)','mục 4 – 22 f)');
insert into NHOM_BENH values('bệnh trẻ em (disease of the children)', 'trí não chậm phát triển (mental retardation), kém chú ý, kém tập trung (mental discocentration)','mục 4 – 22 g)');
insert into NHOM_BENH values('bệnh trẻ em (disease of the children)', 'cận thị (myopia)','mục 4 – 22 h)');
